#!/usr/bin/env python

import sys
import signal
import resource
import subprocess

resource.setrlimit(resource.RLIMIT_FSIZE, (10240, 10240))
signal.alarm(30)
sys.stdout.write(subprocess.Popen(
    ['wget', '-nv', sys.argv[1]],
    stdout=subprocess.PIPE,
    stderr=subprocess.STDOUT).communicate()[0])
