#!/bin/bash

ORIGDIR="$PWD"

pola-nice() {
#    POLA_OPTS=""
#    if [ -e /lib64 ]
#    then
#        POLA_OPTS="$POLA_OPTS -f=/lib64"
#    fi
#    if [ -e /etc/alternatives ]
#    then
#        POLA_OPTS="$POLA_OPTS -f=/etc/alternatives"
#    fi
#
#    mkdir tmpdir.$$
#
#    PATH="$POLA_PATH" \
#        /usr/bin/pola-run -B $POLA_OPTS -f=/proc -f=/opt -tw /tmp tmpdir.$$ -fw=$PWD \
#	-f="$ORIGDIR"/lib/limits --prog="$ORIGDIR"/lib/limits \
#        -a=/usr/bin/nice -a=-n10 \
#        -e "$@"
#
#    rm -rf tmpdir.$$

     nice -n10 /usr/bin/umlbox -n -B -f /opt -T 30 -tw /hackenv . -f "$ORIGDIR/lib" --cwd /hackenv \
         env PATH="$POLA_PATH" "$ORIGDIR/lib/limits" "$@"
}

#pola-nice() {
#    PATH="$POLA_PATH" /usr/bin/nice -n10 "$ORIGDIR"/slox/slox 25 "$@"
#}
