#!/bin/bash

ORIGDIR="$PWD"

pola-nice() {
    POLA_OPTS=""
    if [ -e /lib64 ]
    then
        POLA_OPTS="$POLA_OPTS -f=/lib64"
    fi
    if [ -e /etc/alternatives ]
    then
        POLA_OPTS="$POLA_OPTS -f=/etc/alternatives"
    fi

    mkdir tmpdir.$$

    PATH="$POLA_PATH" \
        /usr/bin/pola-run -B $POLA_OPTS -f=/proc -tw /tmp tmpdir.$$ -fw=. -f=.hg \
        --prog=/usr/bin/nice -a=-n10 \
        -fa="$ORIGDIR"/slox/slox -a=25 \
        -e "$@"

    rm -rf tmpdir.$$
}

#pola-nice() {
#    PATH="$POLA_PATH" /usr/bin/nice -n10 "$ORIGDIR"/slox/slox 25 "$@"
#}
