#!/usr/bin/env python

import os
import sys
import subprocess

http_proxy = 'http://127.0.0.1:3128'
path = '/hackenv/bin:/opt/python27/bin:/opt/ghc/bin:/usr/bin:/bin'
lib = os.path.abspath('lib')

subprocess.call(
    ['nice', '-n10',
     '/usr/bin/umlbox',
     '--no-stdin',
     '--base-mounts',
     '--mount', lib,
     '--translate-write', '/hackenv', os.environ['HACKENV'],
     '--translate', '/hackenv/.hg', os.path.join(os.environ['HACKENV'], '.hg'),
     '--cwd', '/hackenv',
     '--timeout', '30',
     'env', 'PATH=' + path, 'HACKENV=/hackenv', 'http_proxy=' + http_proxy,
     os.path.join(lib, 'limits')] + sys.argv[1:])
